### ISSUE TITLE
Aggregation of spark retrieval rate

### ISSUE THREAD

**Issue by willscott** [davidgasquez/filecoin-data-portal#29]
currently, an individual storage provider shows it's 'mean spark retrieval success rate'
https://filecoinpulse.pages.dev/provider/f02208475/

It would be great to have:
1. retrieval success rate across SPs (ideally as a cumulative distribution function graph)
2. The rate segmented by clients (so the subset of SPs the client has made deals with, and their retrieval success rates)

**Comment by davidgasquez** [comment]
Around 86% of SPs tested by spark have a 0% average retrieval success rate which makes the CDF a bit odd.

![image](https://github.com/davidgasquez/filecoin-data-portal/assets/1682202/eb4908f9-d2e8-4c09-abb2-501e6d9a3aa3)

This is how it looks under the hood of the area chart...

![image](https://github.com/davidgasquez/filecoin-data-portal/assets/1682202/5e962f95-cac9-4ea6-b080-af24f386e82d)

Will push this one and try other visualizations!

**Comment by davidgasquez** [comment]
Couple of quick questions @willscott!

1. I'm computing a `mean_spark_retrieval_success_rate` for all SPs that takes into account all their retrievals history. Does this makes sense for you or should I use a limited 7/30d window for the average?

https://github.com/davidgasquez/filecoin-data-portal/blob/f05d32e369a47ce288a45c240d4200b656ea23d4/dbt/models/filecoin_storage_providers.sql#L110

2. How would you deal with non-tested SPs? I've found that Spark doesn't tests all SPs we have, so when showing the `mean_spark_retrieval_success_rate` value at the client level, it might look odd. E.g: a client with 4 SPs, and only 2 of them have been tested by Spark.

**Comment by willscott** [comment]
1. I'd use a limited window, or an exponential fall-off in weighting

2. maybe a pie chart to show good vs bad within the larger context? or as %'s that don't have to add up to 100%?

**Comment by davidgasquez** [comment]
Pushed an update that surfaces Retrievals at the _Providers List_ level!

https://filecoinpulse.pages.dev/storage_providers/#retrievals

![screenshot-2024-04-24_17:29:23](https://github.com/davidgasquez/filecoin-data-portal/assets/1682202/919f5309-64f2-4b89-afeb-f084ba814234)

Will work on adding SP retrievals on the client level soon!

**Comment by davidgasquez** [comment]
Pushed a new section [on the Client View](https://filecoinpulse.pages.dev/client/f02101558/) that adds a bunch of Client-SP metrics. One of them is the Average Spark Succes Retrieval of the last 7 days.

![image](https://github.com/davidgasquez/filecoin-data-portal/assets/1682202/6694e103-d916-4c59-8740-00386e0abd7a)

Does this works for now?

**Comment by willscott** [comment]
yes. this works well for now!

**Comment by davidgasquez** [comment]
Alright! Closing this one for now then. 

I've opened https://github.com/davidgasquez/filecoin-data-portal/issues/39 to do something similar at the SP level.

Happy to add any metrics that might be interesting at that granularity (client - provider).
