### ISSUE TITLE
Surface Allowance issue number and name

### ISSUE THREAD

**Issue by davidgasquez** [davidgasquez/filecoin-data-portal#31]
Aggregating some feedback from KZ on this issue.

Right now, [inside the allocator's pages](https://filecoinpulse.pages.dev/allocator/f03018494/#3), the Allowance ID numbers listed don't mean much (e.g: 7458). 

It's better to know which application is each allocation and just have the link to github. For example, `(#3)/name (Mongo2store - common crawl)`. And even Github ID (e.g. `amughal`).

**Comment by davidgasquez** [comment]
Heya @willscot! 

Do you know if GH issues for Datacap Applications like https://github.com/cryptowhizzard/Fil-A-2/issues/1 or https://github.com/Destore2023/MetaPathways-Bookkeeping/issues/3 are being indexed by anyone?

Would be great to ingest that information and surface it in a couple of places and was wondering if anyone is doing it to avoid reinventing the wheel!

**Comment by clriesco** [comment]
https://allocator.tech/

**Comment by davidgasquez** [comment]
Thanks @clriesco! Do you know if there is an offifical API for Allocator.tech? 

I see it's doing GET requests to `https://fp-core-prod.dp04sa0tdc6pk.us-east-1.cs.amazonlightsail.com` and I can replicate those but wanted to check before in case there is a better endpoint!

**Comment by clriesco** [comment]
Please, just use github issues. The application is not open for api requests

**Comment by davidgasquez** [comment]
Chatted with Charly and got the :+1: to use the internal API (`/applications`, `/allocators`).

**Comment by davidgasquez** [comment]
We don't need to rely on the previous API endpoints. We can go straight to the repositories and ingest the standarized JSONs (e.g: [`f15lqbrrx6cmkg5o56awnysvqodoalddzpnkildfq` application](https://github.com/FroghubMan/filplus/blob/main/applications/f15lqbrrx6cmkg5o56awnysvqodoalddzpnkildfq.json)).
