### ISSUE TITLE
Legit/Quality/Utility Data Onboarding Chart

### ISSUE THREAD

**Issue by kevzak** [davidgasquez/filecoin-data-portal#32]
We would like to summarize details about Legitimacy/quality of data onboarding

Current example is the top chart from https://compliance.datacapstats.io/

it pulls in data from 3 tools charts below it. 

This Quality Data graph should just be the just dark green section as shown, perhaps in this format:
![image](https://github.com/davidgasquez/filecoin-data-portal/assets/102751751/3d81f366-cb04-42b9-b028-fdb196609722)

**Comment by davidgasquez** [comment]
Heya @kevzak! 

I think the Compilance Datacapstats website might be outdated or not working anymore. The last update was on April 17th. Both CID Checker Bot and Retrieval Bots are now stopped. Will mentioned something about FIDL running the CID Checker Bot but I don't think anyone is running Retrieval Bots. Seems DMOB is not ingesting new data nonetheless.

I have some [custom deal tags](https://github.com/davidgasquez/filecoin-data-portal/blob/main/dbt/models/filecoin_state_market_deals.sql#L23-L40) around piece replication factor across SPs and clients and am also ingesting average daily retrieval data from SPs via Spark. Whith this, I think we could work  on a lightweight alternative if we can clearly define a way to evaluate the "quality" of a `piece_cid`.

> Tooling charts measuring this compliance need improving, robust data, more explanation, more clarity

I think a great start would be clearly defining that makes a `deal_id` being compliant. Is it that the `piece_cid` is replicated in 5 different `provider_id`s? Should these providers also have a minimum retrieval success rate? ... 

If its easier, happy to jump on a call and start figuring things out!

**Comment by kevzak** [comment]
Yes, for sure this site is outdated and will not be updated. We'd like to replace it.

**Comment by kevzak** [comment]
- CID Checker is now running on the allocator repos
- Spark Retrieval tooling and data is a work in progress - @willscott can update you more when and where it will be.

Those would be two of the compliance checks we could utilize toward measuring quality. 

_the piece_cid is replicated in 5 different provider_ids?_ 

Those metrics are going to be measured more by what the allocator said in their profile. Some allocators only require 2 copies. 

_Should these providers also have a minimum retrieval success rate?_ 
This will depend on the data type and compliance type.  If its public open dataset, then yes, we should test an have a threshold.
However, for example, if it is Private, Enterprise Datatype, then retrieval success is not a metric. Instead the compliance metric might be Did the client complete KYC, KYB? or Did the client complete proof of payment?

**Comment by kevzak** [comment]
We need to map out the data type, compliance type a bit better and match with available tooling/data.
