### ISSUE TITLE
Request to show Allocator Performance in a series of views/graphs

### ISSUE THREAD

**Issue by kevzak** [davidgasquez/filecoin-data-portal#34]
First, would be a general allocator graph tree mapping.

RKH

Followed by Meta Allocators (Manual, Marketplace, Auto)

Followed by each Allocator under their tree category. 

![image](https://github.com/davidgasquez/filecoin-data-portal/assets/102751751/8cc9cda6-845d-4884-ac65-82af88e573cd)

**Comment by kevzak** [comment]
Next would be a Sankey style view of the allocator tree to show how much Datacap each allocator tree is using.

Here is an example from LDN dashboard 

![image](https://github.com/davidgasquez/filecoin-data-portal/assets/102751751/30559005-7868-4bfa-b891-e834ae98cfc7)

**Comment by davidgasquez** [comment]
Heya @kevzak! Where can I grab the data related to Meta Allocators (Manual, Marketplace, Auto)?

**Comment by kevzak** [comment]
@davidgasquez - in the json file is listed the 'metapathway type'. https://github.com/filecoin-project/Allocator-Registry/tree/main/Allocators

you can find allocator type there.
