### ISSUE TITLE
Request to show Storage Performance in Graphs/Charts

### ISSUE THREAD

**Issue by kevzak** [davidgasquez/filecoin-data-portal#35]
We want to showcase: Quality + Scale
- of each allocator branch
- Per SP and SP group

Examples of potential details:
- Onboarding speed
- Retrievability
- Whole network	
- Per deal			
- Per sp				
- Per allocator		
- Proof of payment
- Proof of location
- CID distribution

**Comment by davidgasquez** [comment]
Heya @kevzak! These are some great metrics/data points to surface. 

For SPs, I have most of the details you're looking for, but I'm not sure how to link SPs with Allocators.

Let's go through an example with [Greaterheat](https://filecoinpulse.pages.dev/allocator/f03010601/). Right now, I'm ingesting Allocators details data from the [Registry JSONs](https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1041.json).

Now, we also know the clients associated with the Allocator. We derive them from the Allocator Datacap allowances to clients. In this case (Greaterheat), these:

![image](https://github.com/davidgasquez/filecoin-data-portal/assets/1682202/4b2681d1-cd18-4d88-8c87-353a2516305d)

We see than only one client has made deals so far even though 4 have received datacap.

![image](https://github.com/davidgasquez/filecoin-data-portal/assets/1682202/578b7952-6ffa-4e27-8c1e-184de69fac6d)

That client, [f03054012](https://filecoinpulse.pages.dev/client/f03054012), has made deals with [f03044609](https://filecoinpulse.pages.dev/provider/f03044609/).

**Should we link the provider `f03044609` with Greaterheat in this case?**

The [provider is making deals with many more clients](https://filecoinpulse.pages.dev/provider/f03044609/).

![image](https://github.com/davidgasquez/filecoin-data-portal/assets/1682202/ea560808-5010-4572-9845-9f19baafe000)

I would appreciate if you could share how are you linking SPs with Allocators or if there is a better way or alternative source of truth.

**Comment by kevzak** [comment]
Yes, I think you are correct. 

for example:
We have a Manual Meta Allocator Branch we want to show summary data

Under this branch live 65 Manual Allocators (most of the current allocators, including Greater Heat)

What is the performance of the SPs who are storing deals for the clients of the allocators of this branch? vs overall?

I think you are correct. You compile the SPs for each deal for each client for each allocator.

**Comment by kevzak** [comment]
cc @willscott
