### ISSUE TITLE
Request for Allocator Program Metrics

### ISSUE THREAD

**Issue by kevzak** [davidgasquez/filecoin-data-portal#36]
We want to show time to DataCap similar to what was shown in https://clients.datacapstats.io/dashboard

- The Time from when Allocator receives DataCap request to when Allocator distributes
- Avg Time to first allocation: from when Client applies for DataCap  (in a specific allocator, and overall for all allocators) to when Client receives DataCap, could go a step further to when deal lands on chain.
- Average Time to Second DataCap Allocation. Measure second request to when client receives, similar to above

**Comment by davidgasquez** [comment]
Will start looking into these shortly!

> The Time from when Allocator receives DataCap request to when Allocator distributes

Let's say an allocator received datacap on May 1st, and its first allocation was on May 10th. Is that the metric we want to measure or the time it took to "empty" it's Allocator datacap allowance.

> Avg Time to first allocation: from when Client applies for DataCap (in a specific allocator, and overall for all allocators) to when Client receives DataCap, could go a step further to when deal lands on chain.

Looking at the JSON we have available, seems that information is not there.

https://github.com/sxxfuture-official/filplus-allocator-sxxfuture/blob/main/applications/f1ubcvb6eoyzfoan4x32xbmavy6p4khah3i5mxfba.json#L38-L67

Do you know what is the source of truth for `Client applies for DataCap`?
