### ISSUE TITLE
Allocator search by full address

### ISSUE THREAD

**Issue by galen-mcandrew** [davidgasquez/filecoin-data-portal#50]
**Feature Request:**

On the allocators page: https://filecoinpulse.pages.dev/allocators/

1. Add search bar at top, maybe right justified 
2. Allow searching on full address (f1 or f2) in addition to ID (f0)

**Comment by davidgasquez** [comment]
Thanks for the issue @galen-mcandrew!

There is a somewhat hidden search bar at the _Explorer_ level.

https://filecoinpulse.pages.dev/allocators/#explorer

That said, it doesn't include the full address. I need to work on that feature.

Meanwhile, all allocators data and allocations are available at the weekly updated [Allocators Spreadsheet](https://docs.google.com/spreadsheets/d/1uixeylC3pTeOkKh0L2fGsd7YKuyaA6Hse_fhWrm1BIA/edit?gid=0#gid=0). Here, you can search by `allocator_address`!

**Comment by davidgasquez** [comment]
You can now search Allocators by their wallet addresses!

https://filecoinpulse.pages.dev/allocators/#explorer
