### ISSUE TITLE
showing % of DataCap Usage on filecoinpulse allocator chart view

### ISSUE THREAD

**Issue by kevzak** [davidgasquez/filecoin-data-portal#75]
one thing @ Marta (a new team member for FIDL) noticed was it would make reviews much easier if it was possible to add a column showing a percentage of usage column next to Current and Used Allowance PiBs columns.

![image](https://github.com/user-attachments/assets/39732003-d706-4294-a443-1f0935920852)
  

Background: we look to review allocators that have used 75%+ of DataCap allocations and showing a numerical value would make it easier to scan and look to conduct reviews of them

**Comment by davidgasquez** [comment]
There is now an Used Allowance Percent metric there.

![image](https://github.com/user-attachments/assets/d31eef2b-f651-4af4-91d0-2fb07e16737b)
